### ISSUE TITLE
Infinite Pagination

### ISSUE THREAD

**Issue by lindseybradford** [TelegraphCreative/1517org#108]
Example Setup using Infinite Scroll:

[add js module to app](https://github.com/lindseybradford/casebol_design-latest/blob/master/resources/js/app.js#L12)

[define infinite scroll component](https://github.com/lindseybradford/casebol_design-latest/blob/master/resources/js/components/infiniteScroll.js)

Template wise, here's [the list view](https://github.com/lindseybradford/casebol_design-latest/blob/master/templates/work/index.twig). 

The important bits are the [work grid component](https://github.com/lindseybradford/casebol_design-latest/blob/master/templates/work/index.twig#L15), which contains the parent div we want to pull in asynchronously. It has a class we already passed to infinite scroll (in this example it's `.work-grid`).

The other part is the pagination [link to next](https://github.com/lindseybradford/casebol_design-latest/blob/master/templates/work/index.twig#L20); it's class is also included in the Infscroll configs (here, it's `. pagination__next`). 

This would be the most basic example. Paginating filtered lists adds another layer where the pagination next link needs updated to include the url params and queries.

**Comment by johnnymueller** [comment]
Forgot to link this to my PR: https://github.com/TelegraphCreative/1517org/pull/112
