### ISSUE TITLE
Link hover state color on dark b/g

### ISSUE THREAD

**Issue by courtneybradford** [TelegraphCreative/1517org#53]
@lindseybradford When a text link appears on a dark billboard or hero, we need to apply different active and hover state colors so that it passes WCAG 2.0 standards. 

https://www.dropbox.com/s/346vtvxenf8hr5u/Screenshot%202019-05-20%2009.35.07.png?dl=0

**Comment by courtneybradford** [comment]
We may just leave it the same color as other text, use underline to indicate it's a link. There are so many background colors we need to plan for, finding only color for hover instead of two (one for active and one for hover) seems more reasonable…

**Comment by lindseybradford** [comment]
@courtneybradford - Resolved. 

https://www.dropbox.com/s/6j6aqo2eapbie5q/Screen%20Shot%202019-06-05%20at%201.44.27%20PM.png?dl=0

https://www.dropbox.com/s/g8vpicw0auej5zx/Screen%20Shot%202019-06-05%20at%201.44.30%20PM.png?dl=0
